// <auto-generated />
using System;
using MDA.Web.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MDA.Web.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MdaDbContext))]
    [Migration("20251205171315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MDA.Web.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<decimal?>("BuyingPower")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DailyPnl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DividendsPaidYtd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ExcessLiquidity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ExpectedDividendsYear")
                        .HasColumnType("numeric");

                    b.Property<string>("IbkrAccountId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SettledCash")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalPortfolioValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("UnrealizedPnl")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AccountType = "INDIVIDUAL",
                            BaseCurrency = "USD",
                            IbkrAccountId = "U8515462",
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("MDA.Web.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MDA.Web.Domain.Categories.CategoryGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Horizon")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetWeightPercent")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryGoals");
                });

            modelBuilder.Entity("MDA.Web.Domain.Holdings.Holding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<decimal>("RealizedPNL")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("UnrealizedPNL")
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("MDA.Web.Domain.Instruments.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("Ath")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ForwardPe")
                        .HasColumnType("numeric");

                    b.Property<int>("IbkrConId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LastPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("LastPriceUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("Pe")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("Week52High")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IbkrConId")
                        .IsUnique();

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("MDA.Web.Domain.Categories.Category", b =>
                {
                    b.HasOne("MDA.Web.Domain.Accounts.Account", "Account")
                        .WithMany("Categories")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MDA.Web.Domain.Categories.CategoryGoal", b =>
                {
                    b.HasOne("MDA.Web.Domain.Categories.Category", "Category")
                        .WithMany("Goals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MDA.Web.Domain.Holdings.Holding", b =>
                {
                    b.HasOne("MDA.Web.Domain.Accounts.Account", "Account")
                        .WithMany("Holdings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDA.Web.Domain.Categories.Category", "Category")
                        .WithMany("Holdings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MDA.Web.Domain.Instruments.Instrument", "Instrument")
                        .WithMany("Holdings")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("MDA.Web.Domain.Accounts.Account", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("MDA.Web.Domain.Categories.Category", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("MDA.Web.Domain.Instruments.Instrument", b =>
                {
                    b.Navigation("Holdings");
                });
#pragma warning restore 612, 618
        }
    }
}
